// Dados de exemplo mais realistas para o HackTown 2025
// Este arquivo pode ser usado para popular o banco de dados com dados mais variados

const sampleActivities = [
  // Sexta-feira - 01/08/2025
  {
    title: "Abertura Oficial HackTown 2025",
    description: "Cerimônia de abertura com apresentação da programação, palestrantes principais e networking inicial.",
    speaker: "Equipe HackTown",
    date: "2025-08-01",
    start_time: "08:00",
    end_time: "09:00",
    location: "Auditório Principal",
    category: "Institucional",
    tags: "Abertura,Networking,Apresentação",
    difficulty_level: "Iniciante",
    capacity: 500
  },
  {
    title: "O Futuro da Inteligência Artificial no Brasil",
    description: "Discussão sobre tendências, oportunidades e desafios da IA no cenário nacional e internacional.",
    speaker: "Dra. Ana Carolina Silva",
    date: "2025-08-01",
    start_time: "09:30",
    end_time: "10:30",
    location: "Auditório Principal",
    category: "Tecnologia",
    tags: "IA,Futuro,Brasil,Tendências",
    difficulty_level: "Intermediário",
    capacity: 300
  },
  {
    title: "Workshop: Criando Startups no Interior",
    description: "Hands-on sobre como desenvolver e escalar startups fora dos grandes centros urbanos.",
    speaker: "João Pedro Santos",
    date: "2025-08-01",
    start_time: "09:30",
    end_time: "12:00",
    location: "Sala Workshop A",
    category: "Empreendedorismo",
    tags: "Startup,Interior,Escalabilidade,Workshop",
    difficulty_level: "Iniciante",
    capacity: 40
  },
  {
    title: "Blockchain Além das Criptomoedas",
    description: "Aplicações práticas da tecnologia blockchain em supply chain, identidade digital e contratos inteligentes.",
    speaker: "Roberto Costa",
    date: "2025-08-01",
    start_time: "11:00",
    end_time: "12:00",
    location: "Sala de Conferências B",
    category: "Tecnologia",
    tags: "Blockchain,Contratos Inteligentes,Supply Chain",
    difficulty_level: "Avançado",
    capacity: 80
  },
  {
    title: "Design Thinking para Produtos Digitais",
    description: "Metodologia prática para criar produtos centrados no usuário usando design thinking.",
    speaker: "Maria Fernanda Oliveira",
    date: "2025-08-01",
    start_time: "11:00",
    end_time: "12:30",
    location: "Sala Workshop B",
    category: "Design",
    tags: "Design Thinking,UX,Produtos Digitais",
    difficulty_level: "Intermediário",
    capacity: 35
  },
  {
    title: "Painel: Mulheres na Tecnologia",
    description: "Discussão sobre representatividade, desafios e oportunidades para mulheres no setor tech.",
    speaker: "Painel com 4 especialistas",
    date: "2025-08-01",
    start_time: "14:00",
    end_time: "15:30",
    location: "Auditório Principal",
    category: "Diversidade",
    tags: "Mulheres,Tecnologia,Diversidade,Representatividade",
    difficulty_level: "Iniciante",
    capacity: 300
  },
  {
    title: "Desenvolvimento Mobile com Flutter",
    description: "Workshop prático para criar aplicativos multiplataforma usando Flutter e Dart.",
    speaker: "Carlos Eduardo Lima",
    date: "2025-08-01",
    start_time: "14:00",
    end_time: "17:00",
    location: "Lab de Desenvolvimento",
    category: "Desenvolvimento",
    tags: "Flutter,Mobile,Dart,Multiplataforma",
    difficulty_level: "Intermediário",
    capacity: 25
  },
  {
    title: "Sustentabilidade e Green Tech",
    description: "Como a tecnologia pode contribuir para um futuro mais sustentável e práticas ESG.",
    speaker: "Prof. Marcos Sustentável",
    date: "2025-08-01",
    start_time: "16:00",
    end_time: "17:00",
    location: "Auditório Secundário",
    category: "Sustentabilidade",
    tags: "Sustentabilidade,Green Tech,ESG,Meio Ambiente",
    difficulty_level: "Iniciante",
    capacity: 150
  },

  // Sábado - 02/08/2025
  {
    title: "Keynote: O Metaverso e Web3",
    description: "Visão futurista sobre realidade virtual, aumentada e a próxima geração da internet.",
    speaker: "Dr. Felipe Metaverso",
    date: "2025-08-02",
    start_time: "09:00",
    end_time: "10:00",
    location: "Auditório Principal",
    category: "Tecnologia",
    tags: "Metaverso,Web3,VR,AR,Futuro",
    difficulty_level: "Intermediário",
    capacity: 400
  },
  {
    title: "Workshop: React Native do Zero ao Deploy",
    description: "Criação completa de um app mobile desde o desenvolvimento até a publicação nas lojas.",
    speaker: "Juliana React",
    date: "2025-08-02",
    start_time: "09:30",
    end_time: "12:30",
    location: "Lab de Desenvolvimento",
    category: "Desenvolvimento",
    tags: "React Native,Mobile,Deploy,JavaScript",
    difficulty_level: "Intermediário",
    capacity: 30
  },
  {
    title: "Pitch Competition - Startups Inovadoras",
    description: "Competição de pitches com startups locais apresentando soluções inovadoras.",
    speaker: "Startups Participantes",
    date: "2025-08-02",
    start_time: "10:30",
    end_time: "12:00",
    location: "Arena de Pitches",
    category: "Empreendedorismo",
    tags: "Pitch,Startups,Competição,Inovação",
    difficulty_level: "Iniciante",
    capacity: 200
  },
  {
    title: "Cibersegurança para PMEs",
    description: "Estratégias práticas de segurança digital para pequenas e médias empresas.",
    speaker: "Ana Segurança",
    date: "2025-08-02",
    start_time: "11:00",
    end_time: "12:00",
    location: "Sala de Conferências A",
    category: "Segurança",
    tags: "Cibersegurança,PME,Proteção,Estratégias",
    difficulty_level: "Intermediário",
    capacity: 60
  },
  {
    title: "Workshop: Python para Data Science",
    description: "Introdução prática ao uso do Python para análise de dados e machine learning.",
    speaker: "Dr. Pedro Dados",
    date: "2025-08-02",
    start_time: "14:00",
    end_time: "17:00",
    location: "Lab de Data Science",
    category: "Data Science",
    tags: "Python,Data Science,Machine Learning,Análise",
    difficulty_level: "Intermediário",
    capacity: 35
  },
  {
    title: "Marketing Digital para Startups",
    description: "Estratégias de marketing digital com orçamento limitado para startups em crescimento.",
    speaker: "Carla Marketing",
    date: "2025-08-02",
    start_time: "14:00",
    end_time: "15:30",
    location: "Sala Workshop C",
    category: "Marketing",
    tags: "Marketing Digital,Startups,Estratégias,Crescimento",
    difficulty_level: "Iniciante",
    capacity: 50
  },
  {
    title: "Painel: Investimento em Tech no Interior",
    description: "Discussão sobre oportunidades de investimento e funding para empresas tech fora das capitais.",
    speaker: "Investidores e Fundadores",
    date: "2025-08-02",
    start_time: "16:00",
    end_time: "17:30",
    location: "Auditório Principal",
    category: "Investimento",
    tags: "Investimento,Funding,Interior,Venture Capital",
    difficulty_level: "Intermediário",
    capacity: 250
  },

  // Domingo - 03/08/2025
  {
    title: "Workshop: DevOps na Prática",
    description: "Implementação de pipelines CI/CD, containerização e automação de deploys.",
    speaker: "Rafael DevOps",
    date: "2025-08-03",
    start_time: "09:00",
    end_time: "12:00",
    location: "Lab de DevOps",
    category: "Desenvolvimento",
    tags: "DevOps,CI/CD,Docker,Automação",
    difficulty_level: "Avançado",
    capacity: 25
  },
  {
    title: "UX/UI Design: Tendências 2025",
    description: "Principais tendências em design de interfaces e experiência do usuário para o próximo ano.",
    speaker: "Beatriz UX",
    date: "2025-08-03",
    start_time: "09:00",
    end_time: "10:30",
    location: "Sala Design",
    category: "Design",
    tags: "UX,UI,Tendências,Interface,Experiência",
    difficulty_level: "Intermediário",
    capacity: 40
  },
  {
    title: "Inteligência Artificial Generativa",
    description: "Explorando ChatGPT, DALL-E e outras ferramentas de IA generativa para produtividade.",
    speaker: "Dr. IA Generativa",
    date: "2025-08-03",
    start_time: "10:00",
    end_time: "11:30",
    location: "Auditório Principal",
    category: "Tecnologia",
    tags: "IA Generativa,ChatGPT,Produtividade,Automação",
    difficulty_level: "Iniciante",
    capacity: 300
  },
  {
    title: "Workshop: APIs RESTful com Node.js",
    description: "Desenvolvimento de APIs robustas e escaláveis usando Node.js, Express e MongoDB.",
    speaker: "Lucas Backend",
    date: "2025-08-03",
    start_time: "11:00",
    end_time: "14:00",
    location: "Lab de Backend",
    category: "Desenvolvimento",
    tags: "Node.js,API,REST,Express,MongoDB",
    difficulty_level: "Intermediário",
    capacity: 30
  },
  {
    title: "Empreendedorismo Social e Impacto",
    description: "Como criar negócios que geram impacto social positivo e são financeiramente sustentáveis.",
    speaker: "Marina Impacto",
    date: "2025-08-03",
    start_time: "12:00",
    end_time: "13:30",
    location: "Sala de Conferências B",
    category: "Empreendedorismo",
    tags: "Empreendedorismo Social,Impacto,Sustentabilidade",
    difficulty_level: "Iniciante",
    capacity: 70
  },
  {
    title: "Workshop: Cloud Computing com AWS",
    description: "Introdução prática aos serviços da Amazon Web Services para desenvolvedores.",
    speaker: "Especialista AWS",
    date: "2025-08-03",
    start_time: "14:30",
    end_time: "17:30",
    location: "Lab de Cloud",
    category: "Cloud",
    tags: "AWS,Cloud Computing,Infraestrutura,Serviços",
    difficulty_level: "Intermediário",
    capacity: 35
  },
  {
    title: "Painel: Futuro do Trabalho Remoto",
    description: "Discussão sobre tendências, ferramentas e desafios do trabalho remoto pós-pandemia.",
    speaker: "Especialistas em RH e Tech",
    date: "2025-08-03",
    start_time: "15:00",
    end_time: "16:30",
    location: "Auditório Secundário",
    category: "Futuro do Trabalho",
    tags: "Trabalho Remoto,Futuro,Ferramentas,Produtividade",
    difficulty_level: "Iniciante",
    capacity: 150
  },

  // Segunda-feira - 04/08/2025
  {
    title: "Workshop: Machine Learning com Python",
    description: "Implementação prática de algoritmos de ML usando scikit-learn e TensorFlow.",
    speaker: "Dra. ML Python",
    date: "2025-08-04",
    start_time: "09:00",
    end_time: "12:00",
    location: "Lab de IA",
    category: "Data Science",
    tags: "Machine Learning,Python,TensorFlow,Algoritmos",
    difficulty_level: "Avançado",
    capacity: 25
  },
  {
    title: "Fintech e o Futuro dos Pagamentos",
    description: "Inovações em meios de pagamento, PIX, criptomoedas e banking as a service.",
    speaker: "CEO Fintech Inovadora",
    date: "2025-08-04",
    start_time: "09:00",
    end_time: "10:30",
    location: "Auditório Principal",
    category: "Fintech",
    tags: "Fintech,Pagamentos,PIX,Banking,Inovação",
    difficulty_level: "Intermediário",
    capacity: 200
  },
  {
    title: "Workshop: React Hooks Avançados",
    description: "Técnicas avançadas com React Hooks, context API e otimização de performance.",
    speaker: "Expert React",
    date: "2025-08-04",
    start_time: "10:00",
    end_time: "13:00",
    location: "Lab Frontend",
    category: "Desenvolvimento",
    tags: "React,Hooks,Performance,Context API",
    difficulty_level: "Avançado",
    capacity: 30
  },
  {
    title: "Acessibilidade Digital",
    description: "Criando produtos digitais inclusivos e acessíveis para pessoas com deficiência.",
    speaker: "Especialista em Acessibilidade",
    date: "2025-08-04",
    start_time: "11:00",
    end_time: "12:30",
    location: "Sala de Conferências A",
    category: "Acessibilidade",
    tags: "Acessibilidade,Inclusão,WCAG,Design Inclusivo",
    difficulty_level: "Intermediário",
    capacity: 60
  },
  {
    title: "Pitch Final e Premiação",
    description: "Apresentação dos projetos finalistas e cerimônia de premiação do HackTown 2025.",
    speaker: "Equipe HackTown",
    date: "2025-08-04",
    start_time: "14:00",
    end_time: "16:00",
    location: "Auditório Principal",
    category: "Institucional",
    tags: "Pitch,Premiação,Finalistas,Encerramento",
    difficulty_level: "Iniciante",
    capacity: 500
  },
  {
    title: "Networking e Encerramento",
    description: "Momento final de networking, troca de contatos e despedida do HackTown 2025.",
    speaker: "Todos os Participantes",
    date: "2025-08-04",
    start_time: "16:00",
    end_time: "18:00",
    location: "Área de Networking",
    category: "Networking",
    tags: "Networking,Encerramento,Contatos,Despedida",
    difficulty_level: "Iniciante",
    capacity: 1000
  }
];

module.exports = sampleActivities;
